name: "🐞 Bug report"
description: Report a problem
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes: { label: What happened?, description: Clear description, placeholder: "When I ..." }
    validations: { required: true }
  - type: textarea
    id: repro
    attributes: { label: Steps to reproduce, placeholder: "1) ...\n2) ...\n3) ..." }
  - type: input
    id: version
    attributes: { label: KeyPasser version/tag, placeholder: "e.g. 1.2.3 / sha" }
  - type: textarea
    id: env
    attributes: { label: Environment, placeholder: "Docker, compose, OS, DB version, reverse proxy ..." }
  - type: textarea
    id: logs
    attributes: { label: Relevant logs, render: shell }
